

<!DOCTYPE html>

<html lang="ru">

<head>
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="msapplication-tap-highlight" content="no" />
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />
    <link rel="stylesheet" type="text/css" href="../../../../css/read.css" />
    <title>Coder Book menu</title>
    <script type="text/javascript" src="../../../../higtline/scripts/shCore.js"></script>
    <script type="text/javascript" src="../../../../higtline/scripts/shBrushCSharp.js"></script>
    <link type="text/css" rel="stylesheet" href="../../../../higtline/styles/shCoreDefault.css"/>
    <script type="text/javascript">SyntaxHighlighter.all();</script>
    <script src="../../../../js/Hyphenator.js" type="text/javascript"></script>
</head>

<body id="pageBody" class="hyphenate">

<!-- progress bar -->
<script src="../../../../js/progressBar.js" type="text/javascript"></script>
<div class="Reading-progress" id="progressBarType1"><span id="Progress-bar-top" class="bar-top" style="display: block !important;"></span></div>
<div class="Reading-progress" id="progressBarType2"><span id="Progress-bar-bottom" class="bar-bottom"></span></div>
<div class="Reading-progress" id="progressBarType3"><span id="Progress-bar-left" class="bar-left"></span></div>
<div class="Reading-progress" id="progressBarType4"><span id="Progress-bar-right" class="bar-right"></span></div>
<!-- progress bar -->


    <div id="lesonPage">

        <div id="lessMenu">
           <a id="exitLess" href="list.html" ontouchstart="return true;"><img src="../../../../img/menu/ex.png" /></a>
           <div id="aaLess" ontouchstart="return true;" onclick="OpenSettMenu();"><img src="../../../../img/menu/aa.png" /></div>
           <div id="subMenuInLess" style="display: none;">
                <a href="../../../../menu/setfontsize-ru.html" ontouchstart="return true;" id="pastMenuInLess">Размер текста</a>
                <a href="../../../../menu/setcolor-ru.html" ontouchstart="return true;" id="pastMenuInLess">Цветовая темы</a>
                <a href="../../../../menu/setProgressBar-ru.html" ontouchstart="return true;" id="pastMenuInLess" style="border: none;">Прогресс бар</a>
           </div>
           <div id="aaLess" ontouchstart="return true;">
            <div class="bmEdit" onclick="dellBm();" id="bma661" ontouchstart="return true;" style="display: none;"><img src="../../../../img/menu/bmlessa.png" /></div>
            <div class="bmEdit" onclick="setzBm();" id="bm661" ontouchstart="return true;" style="display: block;"><img src="../../../../img/menu/bmless.png" /></div>
           </div>
        </div>

        <hr />

	<!-- ПОЧАТОК -->

	<h1 id="title">
		Ошибки при работе программы. Исключения (Exceptions).
	</h1>

	<p>При выполнении программы могут возникать ошибки. В одних случаях это вызвано ошибками программиста, в других - внешними причинами.</p>
	<p>Например, может возникнуть ошибка ввода/вывода при работе с файлом или сетевым соединением.</p>
	<p>В классических языках программирования, например, в С, требовалось проверять некое условие, которое указывало на наличие ошибки, и в зависимости от этого предпринимать те или иные действия.</p>
	<p>Например:</p>

	<pre class="brush: csharp;">
	...
	int statusCode = someAction();
	
	if (statusCode
	{
		... обработка ошибки
	}
	else
	{
		statusCode = anotherAction();
		
		if(statusCode)
		{
			... обработка ошибки ...
		}
	}
	...
	</pre>

	<p>В Java появилось более простое и элегантное решение - обработка исключительных ситуаций.</p>

	<pre class="brush: csharp;">
	try
	{
		someAction();
		anotherAction();
	}
	catch(Exception e)
	{
		// обработка исключительной ситуации
	}
	</pre>

	<p>Легко заметить, что такой подход является не только изящным, но и более надежным и простым для понимания.</p>

	<h1 id="title">
		Причины возникновения ошибок
	</h1>

	<p>Существует три причины возникновения исключительных ситуаций.</p>
	<p><b>* Попытка выполнить некорректное выражение.</b></p>
	<p>Например, деление на ноль, или обращение к объекту по ссылке, равной null, попытка использовать класс, описание которого ( class -файл) отсутствует, и т.д.</p>
	<p>В таких случаях всегда можно точно указать, в каком месте произошла ошибка, - именно в некорректном выражении.</p>
	<p><b>* Выполнение оператора throw.</b></p>
	<p>Этот оператор применяется для явного порождения ошибки.</p>
	<p>Очевидно, что и здесь можно указать место возникновения исключительной ситуации.</p>
	<p><b>* Асинхронные ошибки во время исполнения программы.</b></p>
	<p>Причиной таких ошибок могут быть сбои внутри самой виртуальной машины (ведь она также является программой), или вызов метода stop() у потока выполнения Thread.</p>
	<p>В этом случае невозможно указать точное место программы, где происходит исключительная ситуация.</p>
	<p>Если мы попытаемся остановить поток выполнения (вызвав метод stop() ), нам не удастся предсказать, при выполнении какого именно выражения этот поток остановится.</p>
	<p>Таким образом, все ошибки в Java делятся на синхронные и асинхронные. С первыми сравнительно проще работать, так как принципиально возможно найти точное место в коде, которое является причиной возникновения исключительной ситуации.</p>
	<p>Конечно, Java является строгим языком в том смысле, что все выражения до точки сбоя обязательно будут выполнены, и в то же время ни одно последующее выражение никогда выполнено не будет.</p>
	<p>Важно помнить, что ошибки могут возникать как по причине недостаточной внимательности программиста (отсутствует нужный класс, или индекс массива вышел за допустимые границы), так и по независящим от него причинам (произошел разрыв сетевого соединения, сбой аппаратного обеспечения, например, жесткого диска и др.).</p>
	<p>Асинхронные ошибки гораздо сложнее в обнаружении и исправлении.</p>
	<p>Обычному разработчику очень трудно выявить причины сбоев в виртуальной машине.</p>
	<p>Это могут быть ошибки создателей JVM, несовместимость с операционной системой, аппаратный сбой и многое другое.</p>
	<p>Все же современные виртуальные машины реализованы довольно хорошо и подобные сбои происходят крайне редко (при условии использования качественных комплектующих).</p>
	<p>Аналогичная ситуация наблюдается и в случае с принудительной остановкой потоков исполнения.</p>
	<p>Поскольку это действие выполняется операционной системой, никогда нельзя предсказать, в каком именно месте остановится поток.</p>
	<p>Это означает, что программа может многократно отработать корректно, а потом неожиданно дать сбой просто из-за того, что поток остановился в каком-то другом месте.</p>
	<p>По этой причине принудительная остановка не рекомендуется.</p>
	<p>В следующей лекции рассматриваются примеры корректного управления жизненным циклом потока.</p>
	<p>При возникновении исключительной ситуации управление передается от кода, вызвавшего исключительную ситуацию, на ближайший блок catch (или вверх по стеку) и создается объект, унаследованный от класса Throwable, или его потомков, который содержит информацию об исключительной ситуации и используется при ее обработке.</p>
	<p>Собственно, в блоке catch указывается именно класс обрабатываемой ситуации.</p>
	<p>Подробно обработка ошибок рассматривается ниже.</p>
	<p>Иерархия, по которой передается информация об исключительной ситуации, зависит от того, где эта исключительная ситуация возникла.</p>
	<p>Если это</p>
	<p>- метод, то управление будет передаваться в то место, где данный метод был вызван;</p>
	<p>- конструктор, то управление будет передаваться туда, где попытались создать объект (как правило, применяя оператор new );</p>
	<p>- статический инициализатор, то управление будет передано туда, где произошло первое обращение к классу, потребовавшее его инициализации.</p>
	<p>Допускается создание собственных классов исключительных ситуаций.</p>
	<p>Осуществляется это с помощью механизма наследования, то есть класс пользовательской исключительной ситуации должен быть унаследован от класса Throwable, или его потомков.</p>

	<h1 id="title">
		Обработка исключительных ситуаций
	</h1>

	<p><b>Конструкция try-catch</b></p>
	<p>В общем случае конструкция выглядит так:</p>

	<pre class="brush: csharp;">
	try
	{
		...
	}
	catch(SomeExceptionClass e)
	{
		...
	}
	catch(AnotherExceptionClass e)
	{
		...
	}
	</pre>

	<p>Работает она следующим образом.</p>
	<p>Сначала выполняется код, заключенный в фигурные скобки оператора try.</p>
	<p>Если во время его выполнения не происходит никаких нештатных ситуаций, то далее управление передается за закрывающую фигурную скобку последнего оператора catch, ассоциированного с данным оператором try.</p>
	<p>Если в пределах try возникает исключительная ситуация, то далее выполнение кода производится по одному из перечисленных ниже сценариев.</p>
	<p>Возникла исключительная ситуация, класс которой указан в качестве параметра одного из блоков catch.</p>
	<p>В этом случае производится выполнение блока кода, ассоциированного с данным catch (заключенного в фигурные скобки).</p>
	<p>Далее, если код в этом блоке завершается нормально, то и весь оператор try завершается нормально и управление передается на оператор (выражение), следующий за закрывающей фигурной скобкой последнего catch.</p>
	<p>Если код в catch завершается не штатно, то и весь try завершается нештатно по той же причине.</p>
	<p>Если возникла исключительная ситуация, класс которой не указан в качестве аргумента ни в одном catch, то выполнение всего try завершается нештатно.</p>
	<p><b>Конструкция try-catch-finally</b></p>
	<p>Оператор finally предназначен для того, чтобы обеспечить гарантированное выполнение какого-либо фрагмента кода.</p>
	<p>Вне зависимости от того, возникла ли исключительная ситуация в блоке try, задан ли подходящий блок catch, не возникла ли ошибка в самом блоке catch - все равно блок finally будет в конце концов исполнен.</p>
	<p>Последовательность выполнения такой конструкции следующая: если оператор try выполнен нормально, то будет выполнен блок finally.</p>
	<p>В свою очередь, если оператор finally выполняется нормально, то и весь оператор try выполняется нормально.</p>
	<p>Если во время выполнения блока try возникает исключение и существует оператор catch, который перехватывает данный тип исключения, происходит выполнение связанного с catch блока.</p>
	<p>Если блок catch выполняется нормально, либо ненормально, все равно затем выполняется блок finally.</p>
	<p>Если блок finally завершается нормально, то оператор try завершается так же, как завершился блок catch.</p>
	<p>Если в списке операторов catch не находится такого, который обработал бы возникшее исключение, то все равно выполняется блок finally.</p>
	<p>В этом случае, если finally завершится нормально, весь try завершится ненормально по той же причине, по которой было нарушено исполнение try.</p>
	<p>Во всех случаях, если блок finally завершается ненормально, то весь try завершится ненормально по той же причине.</p>
	<p>Рассмотрим пример применения конструкции try-catch-finally.</p>

	<pre class="brush: csharp;">
	try
	{
		byte [] buffer = new byte[128];
		FileInputStream fis =
		new FileInputStream("file.txt");
		
		while(fis.read(buffer) > 0)
		{
			... обработка данных ...
		}
	}
	
	catch(IOException es)
	{
		... обработка исключения ...
	}
	
	finally
	{
		fis.flush();
		fis.close();
	}
	</pre>

	<p>Если в данном примере поместить операторы очистки буфера и закрытия файла сразу после окончания обработки данных, то при возникновении ошибки ввода/вывода корректного закрытия файла не произойдет.</p>
	<p>Еще раз отметим, что блок finally будет выполнен в любом случае, вне зависимости от того, произошла обработка исключения или нет, возникло это исключение или нет.</p>
	<p>В конструкции try-catch-finally обязательным является использование одной из частей оператора catch или finally.</p>
	<p>То есть конструкция</p>

	<pre class="brush: csharp;">
	try
	{
		...
	}
	
	finally
	{
		...
	}
	</pre>

	<p>является вполне допустимой.</p>
	<p>В этом случае блок finally при возникновении исключительной ситуации должен быть выполнен, хотя сама исключительная ситуация обработана не будет и будет передана для обработки на более высокий уровень иерархии.</p>
	<p>Если обработка исключительной ситуации в коде не предусмотрена, то при ее возникновении выполнение метода будет прекращено и исключительная ситуация будет передана для обработки коду более высокого уровня.</p>
	<p>Таким образом, если исключительная ситуация произойдет в вызываемом методе, то управление будет передано вызывающему методу и обработку исключительной ситуации должен произвести он.</p>
	<p>Если исключительная ситуация возникла в коде самого высокого уровня (например, методе main()), то управление будет передано исполняющей системе Java и выполнение программы будет прекращено (более точно - будет остановлен поток исполнения, в котором произошла такая ошибка).</p>
	<p><b>Использование оператора throw</b></p>
	<p>Помимо того, что предопределенная исключительная ситуация может быть возбуждена исполняющей системой Java, программист сам может явно породить ошибку.</p>
	<p>Делается это с помощью оператора throw.</p>
	<p>Например:</p>

	<pre class="brush: csharp;">
	...
	public int  calculate(int theValue)
	{
		if( theValue < 0)
		{
			throw new Exception("Параметр для вычисления не должен быть отрицательным");
		}
	}
	...
	</pre>

	<p>В данном случае предполагается, что в качестве параметра методу может быть передано только неотрицательное значение; если это условие не выполнено, то с помощью оператора throw порождается исключительная ситуация.</p>
	<p>(Для успешной компиляции также требуется в заголовке метода указать throws Exception - это выражение рассматривается ниже.)</p>
	<p>Метод должен делегировать обработку исключительной ситуации вызвавшему его коду.</p>
	<p>Для этого в сигнатуре метода применяется ключевое слово throws, после которого должны быть перечислены через запятую все исключительные ситуации, которые может вызывать данный метод.</p>
	<p>То есть приведенный выше пример должен быть приведен к следующему виду:</p>

	<pre class="brush: csharp;">
	...
	public int  calculate(int theValue)
	
	throws Exception
	{
		if( theValue < 0)
		{
			throw new Exception("Some descriptive info");
		}
	}
	...
	</pre>

	<p>Таким образом, создание исключительной ситуации в программе выполняется с помощью оператора throw с аргументом, значение которого может быть приведено к типу Throwable.</p>
	<p>В некоторых случаях после обработки исключительной ситуации может возникнуть необходимость передать информацию о ней в вызывающий код.</p>
	<p>В этом случае ошибка появляется вторично.</p>
	<p>Например:</p>

	<pre class="brush: csharp;">
	...
	try
	{
		...
	}
	
	catch(IOException ex)
	{
		...
		// Обработка исключительной ситуации
		...
		// Повторное возбуждение исключительной ситуации
		throw ex;
	}
	</pre>

	<p>Рассмотрим еще один случай.</p>
	<p>Предположим, что оператор throw применяется внутри конструкции try-catch.</p>

	<pre class="brush: csharp;">
	try
	{
		...
		throw new IOException();
		...
	}

	catch(Exception e)
	{
		...
	}
	</pre>

	<p>В этом случае исключение, возбужденное в блоке try, не будет передано для обработки на более высокий уровень иерархии, а обработается в пределах блока try-catch, так как здесь содержится оператор, который может это исключение перехватить.</p>
	<p>То есть произойдет неявная передача управления на соответствующий блок catch.</p>

	<script src="../../../../js/progressBarSetIni.js" type="text/javascript"></script>

        <div id="lessMenu" style="margin: 30px 0 0 0;">
            <hr />
            <a href="59.html"><div id="exitLess" ontouchstart="return true;"><img src="../../../../img/menu/pr.png" /></div></a>
            <a href="61.html"><div id="aaLess" ontouchstart="return true;"><img src="../../../../img/menu/ne.png" /></div></a>
        </div>

    </div>

    <script type="text/javascript" src="../../../../cordova.js"></script>
    <script type="text/javascript" src="../../../../js/global.js"></script>
    <script type="text/javascript">
        changeColor();
        if (localStorage.getItem("fSize") < 1) { fSize = 16; localStorage.setItem("fSize", 16); } else { fSize = localStorage.getItem("fSize"); }
        document.getElementById("pageBody").style.fontSize = fSize + "px";

        // goBackMenu
        document.addEventListener("backbutton", goBackMenu, false);
        function goBackMenu()
        {
            window.location.href = 'list.html';
        }

        function changeColor()
        {
            if (localStorage.getItem("colorSheme") <= 1)
            {
                document.getElementById("pageBody").style.backgroundColor = localStorage.getItem("#f0f0f0");
            }

            if (localStorage.getItem("colorSheme") == 2)
            {
                document.getElementById("pageBody").style.backgroundColor = localStorage.getItem("#212121");
                document.getElementById("pageBody").style.color = localStorage.getItem("#efefef");
            }

            if (localStorage.getItem("colorSheme") == 3)
            {
                document.getElementById("pageBody").style.backgroundColor = localStorage.getItem("#efe4d0");
            }
        }

        // bm
        if (localStorage.getItem("arrs") != null)
        {
            var arrs = JSON.parse(localStorage.getItem("arrs"));
        }
        else
        {
            var arrs = [];
        }

        var names = ["../acharter/ru/java/book/60.html", "Ошибки при выполнении (ч. 1)", "bm661"];

        function setzBm() { arrs.push(names); localStorage.setItem("arrs", JSON.stringify(arrs)); localStorage.setItem("bm661", 1); RefBms(); }

        window.onload = function() { RefBms(); }

        function RefBms()
        {
            if (localStorage.getItem("bm661") == 1) { document.getElementById("bma661").style.display = "block"; document.getElementById("bm661").style.display = "none"; } else { document.getElementById("bma661").style.display = "none"; document.getElementById("bm661").style.display = "block"; }
        }

        function dellBm() { for (var i = 0; i < arrs.length; i++) { if (arrs[i].indexOf("Ошибки при выполнении (ч. 1)") == 1) { arrs.splice(i, 1); localStorage.setItem("bm661", 0); RefBms(); localStorage.setItem("arrs", JSON.stringify(arrs)); } } }

        // sub menu
        var serTimeToClose = 1000;
        
        function OpenSettMenu()
        {
            document.getElementById("subMenuInLess").style.display = "block";
            timeToEvAct();
            serTimeToClose = 1;
        }
        
        function timeToEvAct()
        {
            setTimeout(function() { serTimeToClose = 0 }, 100);
        }
        
        window.addEventListener('click', function(e){
        
            if (serTimeToClose <= 0)
            {
                if (document.getElementById('subMenuInLess').contains(e.target))
                {
                    //
                }
                else
                {
                    document.getElementById("subMenuInLess").style.display = "none";
                }
            }
        });

    </script>

</body>
</html>
